# Generated by Django 5.1.5 on 2025-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TextField()),
                ('profesores', models.TextField()),
                ('alumnos', models.TextField()),
            ],
        ),
    ]
